FROM fedora:34
ARG RGCV
ARG PYV=3
ARG SINGV=3.8.3

RUN yum install -y git Lmod singularity-${SINGV} findutils python3-pip \
	&& yum clean all

ADD dist/rgc-${RGCV}-py${PYV}-none-any.whl /root/rgc-${RGCV}-py${PYV}-none-any.whl

RUN useradd -m testRGC \
	&& pip3 install /root/rgc-${RGCV}-py${PYV}-none-any.whl \
	&& rm /root/rgc-${RGCV}-py${PYV}-none-any.whl

USER testRGC
WORKDIR /home/testRGC
