FROM quay.io/singularity/singularity:v3.6.4-slim

WORKDIR /root

ADD pkg.tar /root/

RUN apk update \
    && apk add --no-cache py3-pip \
    && pip3 install pytest \
    && find . \
    && pip3 install -e .

ENTRYPOINT ["pytest"]
